### ISSUE TITLE
Question: comparison to 

### ISSUE THREAD

**Issue by bernhardreiter** [postgrespro/testgres#22]
Thanks for creating and publishing testgres as Free Software.

What are the differences to https://github.com/tk0miya/testing.postgresql especially when would one use the one or the other?

What license is testgres under?
(Assuming that publication on https://pypi.python.org/pypi/testgres/0.2.0 means that it shall be Free Software.)

**Comment by funbringer** [comment]
Hi @bernhardreiter,

> What are the differences to https://github.com/tk0miya/testing.postgresql especially when would one use the one or the other?

To be frank, I've never seen this project before, which means that I can't provide a concrete answer to this question. We strive to create a tool that's suitable for us. However, here's an approximate list of testgres' features:

- Aims to look like TAP tests framework provided by PostgreSQL;
- Connection wrapper object (`begin()`, `commit()`, `abort()`, set transaction isolation level);
- Configurable node builder (data directory, various configs, node's name etc);
- It's easy to set up a hot standby / cluster etc;
- pgbench wrapper;
- psql wrapper;
- `get_pid()`, `get_control_data()` (view pg_control), etc.

Please take a look at our [test suite]( https://github.com/postgrespro/pg_pathman/blob/master/tests/python/partitioning_test.py) for pg_pathman if you're interested.

> What license is testgres under?

Thanks, I've just realized that there's no LICENSE file in this repository. The project is released under [the PostgreSQL license](https://www.postgresql.org/about/licence/), of course.

**Comment by bernhardreiter** [comment]
Thanks for the quick response.

For the license I additionally recommend to add it to ```setup.py``.
