### ISSUE TITLE
Directory cached_data_dir did not cleanup after test finished

### ISSUE THREAD

**Issue by sfalkon** [postgrespro/testgres#27]
Directory cached_data_dir did not cleanup after test finished

**Comment by funbringer** [comment]
Hi @sfalkon, good catch!

**Comment by funbringer** [comment]
@ildus, @zilder, I think we should remove cached_data_dir automatically, but it's hard to tell who should be responsible for this action. We could probably add a refcounter and do +1 in `__enter()__` and -1 in `__exit()__` of `PostgresNode`, but that would nullify all the benefits of such cache if only one instance of PostgresNode is active at any time.

**Comment by ildus** [comment]
@funbringer yeah, we can't remove it on `__exit__`. First of all we will need for the next node, and secondly user can start nodes without `with` blocks. I think we should use `atexit` handlers.

**Comment by stalkerg** [comment]
Maybe should user call "clean()" function manually?

**Comment by funbringer** [comment]
Fixed in 1.3.2.
