### ISSUE TITLE
Testgres unavailable on conda-forge

### ISSUE THREAD

**Issue by ilyanoskov** [postgrespro/testgres#95]
Dear Maintainers,

Thank you very much for this project.

Could you please make the package also available on conda-forge?

**Comment by demonolock** [comment]
Hi ilyanoskov, 
Thank you for using. We will send pull request next week and maybe testgres will be added to conda-forge.

**Comment by demonolock** [comment]
Merge request was created https://github.com/conda-forge/staged-recipes/pull/24535

**Comment by demonolock** [comment]
Hi @ilyanoskov, the merge request was merged to conda https://github.com/conda-forge/staged-recipes/pull/24535. The new testgres version 1.10.0 should be there.
