### ISSUE TITLE
'TypeError: decode() argument 'encoding' when node.init()

### ISSUE THREAD

**Issue by michelle0809** [postgrespro/testgres#98]
Hi,
When I try to create a node on port 5435 and execute init(), I get an error 'TypeError: decode() argument 'encoding' must be str, not None'.
Maybe I'm missing some parameter? How can I troubleshoot this error?

python version: 3.11.4
testgres version: 1.9.2

Here is my code.
```
import testgres
with testgres.get_new_node('test', port = 5435) as node:
    print(node)

    node.init()
    node.start()

    print(node.execute('select 1'))

    node.stop()
    node.clean()
```

Error message:
![image](https://github.com/postgrespro/testgres/assets/71964831/0f18557c-d4aa-43ac-81fa-71199b68676f)

[update]
I can excute init() with testgres version 1.8.9.

**Comment by demonolock** [comment]
Hi @michelle0809, thank you for your message!
We will fix it this week.
